select * from person
Select count(*) from person
select * from coach
Select count(*) from coach
select * from trainee
Select count(*) from trainee
select * from gym
Select count(*) from gym
select * from trains_in
Select count(*) from trains_in
select * from hall
Select count(*) from hall
select * from class_lesson
Select count(*) from class_lesson
select * from device
Select count(*) from device
select * from used_in
Select count(*) from used_in
select * from takes
Select count(*) from takes
